name: ML Pipeline CI 
 
on: 
  push: 
    branches: [ kernelridge ] 
  pull_request: 
    branches: [ kernelridge ] 
 
jobs: 
  test-models: 
    runs-on: ubuntu-latest 
 
    steps: 
    - uses: actions/checkout@v3 
 
    - name: Set up Python 
      uses: actions/setup-python@v4 
      with: 
        python-version: '3.9' 
 
    - name: Install dependencies 
      run: pip install -r requirements.txt 
 
    - name: Test Decision Tree Model 
      run: python train.py 
 
    - name: Test Kernel Ridge Model 
      run: python train2.py 
